In [6]:
import pandas as pd
task_list = pd.read_csv('../step1-task_list/task_art.csv', sep='\t')[['occupation', 'task']]
task_list.drop_duplicates().to_csv('../data/en/task_occupation.csv', index=None, sep='\t')
task_list

,occupation,task
0,Accountants and Auditors,Prepare detailed reports on audit findings.
1,Accountants and Auditors,Report to management about asset utilization a...
2,Accountants and Auditors,Collect and analyze data to detect deficient c...
3,Accountants and Auditors,Inspect account books and accounting systems f...
4,Accountants and Auditors,"Supervise auditing of establishments, and dete..."
...,...,...
18884,Zoologists and Wildlife Biologists,Conduct literature reviews.
18885,Zoologists and Wildlife Biologists,Organize and conduct experimental studies with...
18886,Zoologists and Wildlife Biologists,Coordinate preventive programs to control the ...
18887,Zoologists and Wildlife Biologists,Prepare collections of preserved specimens or ...
18888,Zoologists and Wildlife Biologists,Collect and dissect animal specimens and exami...