In [3]:
import os
import pandas as pd
dataset_name = 'jp'
df = pd.read_csv(f'../data/{dataset_name}/job_description.csv', sep='\t')
df = df[df['job_description'].apply(type)==type('')]
df = df[df['job_description'].apply(len)> 0]
df = df.drop_duplicates('job_description')
df.columns = ['job_title', 'job_description']
if not os.path.exists(f'data/{dataset_name}'):
    os.makedirs(f'data/{dataset_name}')
df.to_csv(f'data/{dataset_name}/job_description.csv', index=None, sep='\t')
df

,job_title,job_description
0,データ入力・修正,データ入力・修正\n朝１０時開始！みんな未経験から始めてます。高速バス料金比較サイトのデータ...
1,SNS運用データ入力/週払いのできるオフィスワーク,\n \n 週払いOK！勤務中の飲食自由働きやすさ抜群！ピアス・ネイル・タトゥ・髪色完全自...
2,PCデータ入力(SNS運用),★新規事業立ち上げ★オープニングメンバー！服装/髪色/ピアス/タトゥ自由◎\n\n\n駅チカ...
5,恋愛シミュレーションゲームのデータ入力/企画・事務・管理系,恋愛シミュレーションゲームのデータ入力(未経験歓迎) 服装自由/週2日×1日3時間からOK ...
6,データ入力,\n \n 未経験者歓迎PCのタイピングができればOKピアス/ネイル/タトゥ/週払い/完全...
...,...,...
3371,新卒採用 システムエンジニア/プログラマ(福岡市),\n \n ハローワーク求人番号\n \n \n 13010-00179048...
3372,新卒採用 【25卒】自動運転分野を含む車載ソフトにおけるデータ分析・ソリューション/ソフトウ...,\n 最先端のソフトウェア技術を日常の技術へ先進安全機能や自動運転で注目を集める自動車産業。...
3373,新卒採用 システムエンジニア プログラマー,\n \n ハローワーク求人番号\n \n \n 14090-00040048...
3374,JavaScript/ソーシャルゲーム会社向け社内システム開発,案件名:\nJavaScript/ソーシャルゲーム会社向け社内システム開発案件・求人\n\n...
3377,SE(制御系),ロボットを思い通り動かす喜び!ロボットアニメ世代ですから(笑: といってもあの戦闘ロボットの...

In [5]:
import re
 
# 示例字符串
text = "IP: 192.168.1.1 Port: 80"
 
# 正则表达式
pattern = ":"
 
# 使用正则表达式进行匹配
matches = re.findall(pattern, text)
 
# 输出匹配结果
for match in matches:
    print(match)

:
: