In [24]:
import pandas as pd
dataset_name = 'jp'
# df = pd.read_csv(f'outputs/{dataset_name}/job_re_description.csv', sep='\t').groupby(['job_title', 'job_description']).agg(list).reset_index()

df = pd.read_parquet(f'outputs/{dataset_name}/job_re_description.parquet')
print('match jd num', len(df[df['len']>0]))
filter_df = df[df['len']>1]
print('num of extracted job task:', filter_df['len'].sum().item())
filter_df

match jd num 21
num of extracted job task: 39

,job_title,job_description,task,len
163,ITエンジニア／月給35万以上／賞与年3回／豊富な案件あり,【企業名】\n\nスイングバイテクノロジー株式会社\n\n【職種名】\n\nITエンジニア／...,"[日) 【休暇「GW休暇」に対するフリー入力欄】 (昨年度実績, 日) 【休暇「夏季休暇」に...",7
44,ITエンジニア／未経験歓迎／リモート勤務／賞与実績4カ月,【企業名】 ＩＴＢＲＯＮＸ合同会社 【職種名】 ITエンジニア／未経験歓迎／リモート勤務／賞...,"[入社1～2カ月：座学＋基礎研修, 入社3カ月目～：実際にプロジェクトに参画してのOJT, ...",5
140,グローバルICTエンジニア（提案／開発／設計・構築／監視）,【企業名】\n\nNTTコム エンジニアリング株式会社（※NTTコミュニケーションズグループ...,"[本社：東京都港区芝浦1-2-1 シーバンスN館, 札幌：札幌市中央区, 仙台：仙台市宮城野...",5
57,【全国どこでも勤務可/フルリモート】RPAエンジニア/UiPath経験者大歓迎■大和ハウスグループ,【企業名】\n\n株式会社メディアテック（大和ハウスグループ）\n\n【職種名】\n\n【全...,"[UiPath, VB.NET, AI-OCR, MySQL など]",4
91,【麻布十番】開発エンジニア～20名程の少数精鋭組織で部門の責任者を目指せる/残業10h以内～,【企業名】\n\n株式会社ｉｎｓｐｒｏｕｔ\n\n【職種名】\n\n【麻布十番】開発エンジニ...,"[ベンチャー支援事業, インベストメント事業, コーポレートベンチャリング支援, システム開...",4
96,ECマーケットプレイス開発：Webエンジニア 楽天リーベイツ,Job Description\n\n部署・サービスについて\n\nリーベイツ開発グループは...,"[ビジネス要件を理解し、高い品質とスピードで機能を提供, Eコマースシステムの設計、開発、テ...",4
97,【グループIT推進本部】インフラエンジニア・SREエンジニア,部署紹介\n\nIDガバナンス局は、2023年10月に新設された組織で、社内ID管理、権限管...,"[立場の異なる関係者に対して粘り強く交渉を進めることができる方, 理想を見据えつつ現実と向き...",3
158,急成長ディープテック！Webエンジニア募集！新たなプロダクト開発に挑む！,【企業名】\n\n株式会社マップフォー\n\n【職種名】\n\n急成長ディープテック！Web...,"[給与は経験・能力を考慮の上決定します。, 月額給与は年俸を12で除した値とする, 賞与：業...",3
69,【回路設計エンジニア】勤務地希望可（転勤無し）：福岡県、広島県※中国・九州エリア,【企業名】\n\n株式会社ヒップ\n\n【職種名】\n\n【回路設計エンジニア】勤務地希望可...,"[広島エリア, 福岡エリア]",2
103,【フルリモート可】アプリ開発エンジニア◆自社開発／残業15hほど／子育て・医療等の社会貢献性◎,【企業名】\n\n株式会社ミラボ\n\n【職種名】\n\n【フルリモート可】アプリ開発エンジ...,[子育てモバイル：子育て情報の発信（医療機関・子育て施設情報等）、保育園の電子手続き・予防接...,2

In [5]:
import os
filter_df = filter_df[['job_title', 'task']]
filter_df = filter_df.explode('task')
filter_df = filter_df.drop_duplicates('task')
filter_df

,job_title,task
400,Préposé imagerie,Réception au bureau d’<anon_misc>
400,Préposé imagerie,Accueillir les visiteurs à raison de 3.5 heure...
400,Préposé imagerie,Traitement de formulaires
400,Préposé imagerie,Travailler en mode simultané avec les logiciel...
400,Préposé imagerie,Rechercher l’investisseur selon certains critè...
...,...,...
164,Préposé aux ventes (TSAG),Faire la sollicitation téléphonique auprès de ...
164,Préposé aux ventes (TSAG),Effectuer toute autre tâche connexe.
191,Préposé aux ventes,Faire de la sollicitation téléphonique auprès ...
446,Préposé à la mise sous contrat,Gérer la boîte courriel en lien avec le proces...
446,Préposé à la mise sous contrat,Agir en tant qu’intermédiaire entre notre forc...

In [6]:
len(filter_df)

256

In [7]:
if dataset_name == 'jp':
    filter_df['task_len'] = filter_df['task'].apply(len)
else:
    filter_df['task_len'] = filter_df['task'].apply(lambda x: len(x.split(' ')))
# filter_df = filter_df.sort_values('task_len', ascending=False)
filter_df = filter_df[filter_df['task_len']>3]
filter_df

,job_title,task,task_len
400,Préposé imagerie,Réception au bureau d’<anon_misc>,4
400,Préposé imagerie,Accueillir les visiteurs à raison de 3.5 heure...,19
400,Préposé imagerie,Travailler en mode simultané avec les logiciel...,14
400,Préposé imagerie,Rechercher l’investisseur selon certains critè...,16
400,Préposé imagerie,Compléter certaines informations qui permettro...,10
...,...,...,...
164,Préposé aux ventes (TSAG),Faire la sollicitation téléphonique auprès de ...,8
164,Préposé aux ventes (TSAG),Effectuer toute autre tâche connexe.,5
191,Préposé aux ventes,Faire de la sollicitation téléphonique auprès ...,9
446,Préposé à la mise sous contrat,Gérer la boîte courriel en lien avec le proces...,33
446,Préposé à la mise sous contrat,Agir en tant qu’intermédiaire entre notre forc...,20

In [8]:
if not os.path.exists(f'results/{dataset_name}'):
    os.makedirs(f'results/{dataset_name}')
filter_df.to_csv(f'results/{dataset_name}/job_re_description.csv', index=None, sep='\t')
filter_df.to_excel(f'results/{dataset_name}/{dataset_name}-job_re_description.xlsx', index=None)