In [2]:
import os
import pandas as pd
dataset_name = 'en'
all_data_task_topk = pd.read_csv('../step2-task_map_occupation/outputs/en/all_data_task_topk.csv', sep='\t')
all_data_task_topk['task_candidate'] = all_data_task_topk.apply(lambda x: [x[f"task{i}"] for i in range(10)], axis=1)
all_data_task_topk = all_data_task_topk[['occupation', 'task', 'task_candidate']]
all_data_task_topk.to_parquet(f'data/{dataset_name}/task_topkoccupation.parquet')
all_data_task_topk = all_data_task_topk.reset_index()
all_data_task_topk.columns = ['index', 'occupation', 'job description', 'occupation_candidate']
all_data_task_topk = all_data_task_topk[['index', 'job description', 'occupation_candidate']]
for seed in range(5):
    if not os.path.exists(f'data/{dataset_name}/seed{seed}/input0'):
        os.makedirs(f'data/{dataset_name}/seed{seed}/input0')
    all_data_task_topk.to_parquet(f'data/{dataset_name}/seed{seed}/input0/task_candidate.parquet')
all_data_task_topk

,index,job description,occupation_candidate
0,0,Agent Assistance- Receive & Organize Marketing...,"[Search Marketing Strategists, Sales Represent..."
1,1,"At Aspen Therapy and Wellness , we are committ...","[Self-Enrichment Teachers, Residential Advisor..."
2,2,We are actively looking to hire a therapist in...,"[Self-Enrichment Teachers, Fitness and Wellnes..."
3,3,Senior Associate Attorney - Elder Law / Trusts...,"[Self-Enrichment Teachers, Residential Advisor..."
4,4,Children's is committed to diversity and inclu...,"[Self-Enrichment Teachers, Residential Advisor..."
...,...,...,...
10897,10897,"Through comprehensive training, meaningful rec...","[Self-Enrichment Teachers, Business Continuity..."
10898,10898,We are committed to providing equal employment...,"[Eligibility Interviewers, Government Programs..."
10899,10899,We are committed to building a team that repre...,"[Self-Enrichment Teachers, Sustainability Spec..."
10900,10900,"We believe that the outdoors are for everyone,...","[Self-Enrichment Teachers, Sustainability Spec..."
10901,10901,The company recently took on a private equity ...,"[Residential Advisors, Sustainability Speciali..."